### ISSUE TITLE
k_est is negative

### ISSUE THREAD

**Issue by mfader** [sinanshi/LPJmL_Calibration#12]
not like in the samurai version. I guess negative is standard value? But I can not show that in that way...

**Comment by mfader** [comment]
So this problem refers to the legend of the map. A connected problem is in the crop version, where for all crops the legend should go from 1 to 7 and not from the minimum LAI max to the maximum one.

**Comment by sinanshi** [comment]
you have to update the values in /src/tree_dens.csv, i.e. 7 columns start from 1 - 7. I don't know if you mean that or not.

**Comment by mfader** [comment]
In the crop version this file is not used, so it shouldn't have any influence changing it.
