### ISSUE TITLE
Citrus

### ISSUE THREAD

**Issue by mfader** [sinanshi/LPJmL_Calibration#17]
There are two weird thing in Citrus: 
-one very small point (=bubble) without a cross.
-Croatia, which is almost on the line, appears blue, which is a strong overestimation. kind of unlogical...

**Comment by sinanshi** [comment]
can you send me your plot by email, just citrus.

**Comment by mfader** [comment]
![lpjmlcalib_vs_fao_all_citrus](https://cloud.githubusercontent.com/assets/11858785/7631592/7ee0ef18-fa44-11e4-95a1-814417962bb4.png)

**Comment by mfader** [comment]
samurai version: 
![lpjmlcalib_vs_fao_all_citrus](https://cloud.githubusercontent.com/assets/11858785/7632654/7dd1cd80-fa4f-11e4-8c25-d89cf1df9928.png)

**Comment by mfader** [comment]
also interesting: general lack of blue points in the plots: results are like this or is there a problem with the plotting of blue dots?

**Comment by sinanshi** [comment]
About the blue dot, on the graph is also pretty logical. According to the graph, LPJ value is around 2 and fao is less than 1. But I will double check on that still.

**Comment by sinanshi** [comment]
I can check the value of Crotia, however I don't know how verify the issue of lacking of blue. Do you have any idea?

**Comment by mfader** [comment]
about Croatia, makes sense I guess. I just "discover" that this way the smaller the values, the more sensible reacts the script for showing outliers.

**Comment by sinanshi** [comment]
em, what I can do is to put another two lines, one is the over estimate line, one is the underestimate line, just for testing, I can do that now, which is the easiest way

**Comment by mfader** [comment]
you mean printing to the screen the actual overestimated values? sounds good

**Comment by sinanshi** [comment]
No, you will see, I update you the graph in a min.

**Comment by mfader** [comment]
I am just thinking that maybe the problem is that the red and blue plotting is not symetric: 200% versus 50%

**Comment by sinanshi** [comment]
You are right, it should be 150% instead.

**Comment by mfader** [comment]
right, I can test myself what is the putcome of that!

**Comment by mfader** [comment]
well, delivers no change except for one dot in pulses, apparently we just do not overestimate yields a lot :-)

**Comment by mfader** [comment]
I also checked the codes in the plotting of blue dots, I cannot see any bugs, I guess it is just the results are like that

**Comment by sinanshi** [comment]
![lpjmlcalib_vs_fao_all_citrus](https://cloud.githubusercontent.com/assets/1120679/7635750/a2f29792-fa5a-11e4-8d10-96ddd0c3852e.png)
![lpjmlcalib_vs_fao_all_date_palm](https://cloud.githubusercontent.com/assets/1120679/7635753/a2f31834-fa5a-11e4-95cc-2bd33f68fe36.png)
![lpjmlcalib_vs_fao_all_grapes](https://cloud.githubusercontent.com/assets/1120679/7635751/a2f2a840-fa5a-11e4-87e4-9b0ca194618f.png)
![lpjmlcalib_vs_fao_all_nuts_trees](https://cloud.githubusercontent.com/assets/1120679/7635748/a2f1c542-fa5a-11e4-99c6-cfda71bf700c.png)
![lpjmlcalib_vs_fao_all_olives](https://cloud.githubusercontent.com/assets/1120679/7635749/a2f1f314-fa5a-11e4-9fb2-2d4717f82d26.png)
![lpjmlcalib_vs_fao_all_orchards](https://cloud.githubusercontent.com/assets/1120679/7635752/a2f2bb6e-fa5a-11e4-8f12-686d8b334a12.png)

**Comment by mfader** [comment]
very interesting!

**Comment by sinanshi** [comment]
interestingly, I got more dots. :-)

**Comment by mfader** [comment]
yes! and you lost crosses (e.g. in date palm) (mmmhhhh....scratching head)

**Comment by sinanshi** [comment]
ah, what I have only changed it the duplicated green points line

**Comment by sinanshi** [comment]
well, I will sort it out, this is our last task!

**Comment by mfader** [comment]
which one did you let in in the green dots plotting?

**Comment by sinanshi** [comment]
The second one.

**Comment by mfader** [comment]
two things: 
-I think in the first line you plot everybody which is not zero. That is the right one. The second one only plottet when one is bigger than the other. Or I am wrong?
-Second thing: Some if functions in R evaluate only the first element in an array, not elementwise. This is the difference between the functions if() else() and ifelse(), and also, the difference between using the connector && and &, if I am not remembering wrong. I am guessing the bug of the black dots is in one of these things. And that could also explain maybe the lost crosses...

**Comment by sinanshi** [comment]
I'm looking at these, you are right!! I'm a bit slow, give me some moment.

**Comment by sinanshi** [comment]
No, the first line is correct and the second line is completely stupid! To plot green cross while LPJ yields are larger than FAO. What is that?| It's only stupidity! I have removed the second line, and there is no problem. The black dot can only be made by symbol. 

```
circle.radius <- lpj.area/max(lpj.areas)*max(fao.yields)
```

if fao.area is zero,  and lpj.area is not zero, then circle.radius is not zero too. That is the problem!

**Comment by mfader** [comment]
ok for the green crosses plotting.

for the black dots: I don't understand what you say. FAO areas are not in the equation... And aso, I don't understand why you divide by 5

**Comment by mfader** [comment]
and also, parenthesis are a really cool thing when mixing division and multiplication ;-)

**Comment by sinanshi** [comment]
ask yourself :-D

**Comment by sinanshi** [comment]
Look at your own code, the previous Christoph's code.

**Comment by mfader** [comment]
ah ja, I remeber, they were too huge if not. In our defense, we did use parenthesis :-D

**Comment by sinanshi** [comment]
Very good.

**Comment by sinanshi** [comment]
They are solved in the latest version! Can you have a check and close this issue in due course. Thanks
