### ISSUE TITLE
about the country label

### ISSUE THREAD

**Issue by sinanshi** [sinanshi/LPJmL_Calibration#5]
- please see plots/ we put all the countries label. They will always have a superpose problem.
- Solutions:
  - Like what we used to do, to plot the countries that only have significant areas.
  - Look at the plot and implement them manually.

**Comment by mfader** [comment]
I will look what to do with this. The labels as they are are not usable since they are coloured (instead of black) and supperimposed with the center instead of next to the center. So even solving the problem of supperimposing between different bubbles, they could not be used.

**Comment by sinanshi** [comment]
1. I intentionally set it in the centre of the cross, because otherwise, some text will be out of boundary. 
2. you can change them to black which is easy. I will really suggest to plot one graph without and country label and put them by hand. It can solve this problem. 
3. For the purpose of propaganda, it is also not very good to put label everywhere, since you got people's atraction only on these insignificant countries. But as Alberte said, you'd better do that.

**Comment by sinanshi** [comment]
Text putting part is in plot_tree.r `line 110-120`

```
  if(length(index.put)!=0){
      text(fao.yields[b,index.put],best_yields[b,index.put]-0*(max(best_yields[b,],na.rm=T)),
           selectcountryname[index.put] , cex=.6)
  }

```

You can change freely the font (`cex`), the position, by modify the`0` in `0*(max(best_yields[b,])` to make the text go up and down, left and right.
