### ISSUE TITLE
Not sure you are using the latest output version

### ISSUE THREAD

**Issue by mfader** [sinanshi/LPJmL_Calibration#8]
compared plot attached
![lpjmlcalib_vs_fao_all_nuts_trees](https://cloud.githubusercontent.com/assets/11858785/7414194/53fef860-ef51-11e4-85a8-1dc8284a7782.png)

**Comment by sinanshi** [comment]
You are right. But I have checked the rest of the plot they are exactely the same. I will assume even they are in different version, they should be near.

**Comment by mfader** [comment]
legend was masking dots, it is the same version
